// Build-time modules. Their values are generated by scripts/browser-runtime/build.mjs.
declare module '*build-info.js' {
  export const buildInfo: Readonly<import('./types.js').BuildInfo>;
}
declare module '*bindings.mjs' {
  const createBindings: () => import('./bindings.js').Bindings;
  export default createBindings;
}
